<?xml version="1.0" encoding="UTF-8"?>
<con:wsdlEntry xmlns:con="http://www.bea.com/wli/sb/resources/config">
    <con:wsdl><![CDATA[<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/BPMServiceTest/Project1/db_serv" name="db_serv-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/BPMServiceTest/Project1/db_serv" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/BPMServiceTest/Project1/db_serv" location="db_serv.wsdl"/>
  <binding name="db_serv_ptt-binding" type="tns:db_serv_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="db_servSelect">
      <soap:operation soapAction="db_servSelect"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="db_serv-service">
    <port name="db_serv-port" binding="tns:db_serv_ptt-binding">
      <soap:address location="jca://myConnPoolForDB"/>
    </port>
  </service>
</definitions>]]></con:wsdl>
    <con:dependencies>
        <con:import location="db_serv.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/BPMServiceTest/Project1/db_serv">
            <con:wsdl ref="OSB_DB_ADAPTERS/Drugstore2_ADAPTER/db_serv"/>
        </con:import>
    </con:dependencies>
    <con:targetNamespace>http://xmlns.oracle.com/pcbpel/adapter/db/BPMServiceTest/Project1/db_serv</con:targetNamespace>
</con:wsdlEntry>