<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../xsd/ds1_db_service_table.xsd"/>
      <rootElement name="ProductCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/ds1_db_service"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../xsd/db_serv_table.xsd"/>
      <rootElement name="MedicinedrugCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/db_serv"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.0(build 130301.0647.0008) AT [TUE OCT 27 07:36:15 PDT 2015]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/db/top/db_serv"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/top/ds1_db_service"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:bpmn="http://schemas.oracle.com/bpm/xpath"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl ns0 xsd ns1 bpws xp20 mhdr bpel oraext dvm hwf med ids bpm xdk xref bpmn ora socket ldap">
  <xsl:template match="/">
    <ns1:MedicinedrugCollection>
      <xsl:for-each select="/ns0:ProductCollection/ns0:Product">
        <ns1:Medicinedrug>
          <ns1:id>
            <xsl:value-of select="ns0:id"/>
          </ns1:id>
          <xsl:if test="ns0:name">
            <ns1:name>
              <xsl:if test="ns0:name/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="ns0:name/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="ns0:name"/>
            </ns1:name>
          </xsl:if>
          <ns1:invimacod>
            <xsl:text disable-output-escaping="no">na</xsl:text>
          </ns1:invimacod>
          <ns1:record>
            <xsl:text disable-output-escaping="no">0</xsl:text>
          </ns1:record>
          <ns1:unit>
            <xsl:text disable-output-escaping="no">na</xsl:text>
          </ns1:unit>
          <ns1:atc>
            <xsl:text disable-output-escaping="no">na</xsl:text>
          </ns1:atc>
          <ns1:atcdesc>
            <xsl:text disable-output-escaping="no">na</xsl:text>
          </ns1:atcdesc>
          <ns1:administration>
            <xsl:text disable-output-escaping="no">na</xsl:text>
          </ns1:administration>
          <ns1:pharmform>
            <xsl:text disable-output-escaping="no">na</xsl:text>
          </ns1:pharmform>
          <ns1:manufacturer>
            <xsl:text disable-output-escaping="no">na</xsl:text>
          </ns1:manufacturer>
          <ns1:drugstoreid>
            <xsl:text disable-output-escaping="no">1</xsl:text>
          </ns1:drugstoreid>
          <xsl:if test="ns0:price">
            <ns1:commercialprice>
              <xsl:value-of select="ns0:price"/>
            </ns1:commercialprice>
          </xsl:if>
        </ns1:Medicinedrug>
      </xsl:for-each>
    </ns1:MedicinedrugCollection>
  </xsl:template>
</xsl:stylesheet>
