<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="XSD">
      <schema location="http://soabpm-vm.site:7001/test4/getGenerics/getGenerics_Proxy?SCHEMA%2Ftest4%2FgetGenerics%2FgetGenerics"/>
      <rootElement name="getGenericsOutputCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/getGenerics"/>
      <param name="genericsOutputCollection" />
    </source>
  </mapSources>
  <mapTargets>
    <target type="XSD">
      <schema location="http://soabpm-vm.site:7001/OTHER_SERVICES/RoutingMedicineSearch/OSB_GetMedicine2_Proxy?SCHEMA%2FOTHER_SERVICES%2FRoutingMedicineSearch%2FXMLSchema_1000039831"/>
      <rootElement name="SetOfMedicines" namespace="http://xmlns.oracle.com/bpm/bpmobject/MyTipes/SetOfMedicines"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.0(build 130301.0647.0008) AT [SAT NOV 21 15:24:19 PST 2015]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:ns1="http://xmlns.oracle.com/bpm/bpmobject/MyTipes/SetOfMedicines"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:ns2="http://xmlns.oracle.com/bpm/bpmobject/MyTipes/Medicine"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:bpmo="http://xmlns.oracle.com/bpm/bpmobject/"
                xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/getGenerics"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:bpmn="http://schemas.oracle.com/bpm/xpath"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl ns0 xsd ns1 ns2 bpmo bpws xp20 mhdr bpel oraext dvm hwf med ids bpm xdk xref bpmn ora socket ldap">
  <xsl:template match="/">
    <ns1:SetOfMedicines>
      <xsl:for-each select="/ns0:getGenericsOutputCollection/ns0:getGenericsOutput">
        <ns1:medicines>
          <ns2:name>
            <xsl:if test="ns0:medicine/@xsi:nil">
              <xsl:attribute name="xsi:nil">
                <xsl:value-of select="ns0:medicine/@xsi:nil"/>
              </xsl:attribute>
            </xsl:if>
            <xsl:value-of select="ns0:medicine"/>
          </ns2:name>
          <ns2:invima_code>
            <xsl:text disable-output-escaping="no"></xsl:text>
          </ns2:invima_code>
          <ns2:record>
            <xsl:text disable-output-escaping="no"></xsl:text>
          </ns2:record>
          <ns2:unit>
            <xsl:text disable-output-escaping="no"></xsl:text>
          </ns2:unit>
          <ns2:atc>
            <xsl:text disable-output-escaping="no"></xsl:text>
          </ns2:atc>
          <ns2:atc_description>
            <xsl:text disable-output-escaping="no"></xsl:text>
          </ns2:atc_description>
          <ns2:administration>
            <xsl:text disable-output-escaping="no"></xsl:text>
          </ns2:administration>
          <ns2:active_principle>
            <xsl:text disable-output-escaping="no"></xsl:text>
          </ns2:active_principle>
          <ns2:pharmaceutical_form>
            <xsl:text disable-output-escaping="no"></xsl:text>
          </ns2:pharmaceutical_form>
          <ns2:manufacturer>
            <xsl:if test="ns0:manufacturer/@xsi:nil">
              <xsl:attribute name="xsi:nil">
                <xsl:value-of select="ns0:manufacturer/@xsi:nil"/>
              </xsl:attribute>
            </xsl:if>
            <xsl:value-of select="ns0:manufacturer"/>
          </ns2:manufacturer>
          <ns2:drugstore_id>
            <xsl:text disable-output-escaping="no"></xsl:text>
          </ns2:drugstore_id>
          <ns2:commercial_price>
            <xsl:text disable-output-escaping="no"></xsl:text>
          </ns2:commercial_price>
        </ns1:medicines>
      </xsl:for-each>
    </ns1:SetOfMedicines>
  </xsl:template>
</xsl:stylesheet>
