<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="XSD">
      <schema location="http://soabpm-vm.site:7001/BPM_SERVICES/FindNearestDrugstore_BPM_Service/FindNearestDrugstore_Proxy?SCHEMA%2FBPM_SERVICES%2FFindNearestDrugstore_BPM_Service%2FXMLSchema_-1309485453"/>
      <rootElement name="SetOfDrugstores" namespace="http://xmlns.oracle.com/bpm/bpmobject/MyTipes/SetOfDrugstores"/>
      <param name="list_drugstores" />
    </source>
  </mapSources>
  <mapTargets>
    <target type="XSD">
      <schema location="../businessCatalog/MyTipes/SetOfDrugstoreMedicines.xsd"/>
      <rootElement name="SetOfDrugstoreMedicines" namespace="http://xmlns.oracle.com/bpm/bpmobject/MyTipes/SetOfDrugstoreMedicines"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.0(build 130301.0647.0008) AT [MON NOV 16 17:49:41 PST 2015]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:ns0="http://xmlns.oracle.com/bpm/bpmobject/MyTipes/SetOfDrugstores"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:ns4="http://xmlns.oracle.com/bpm/bpmobject/MyTipes/Medicine"
                xmlns:bpmo="http://xmlns.oracle.com/bpm/bpmobject/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ns1="http://xmlns.oracle.com/bpm/bpmobject/MyTipes/Drugstore"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:ns2="http://xmlns.oracle.com/bpm/bpmobject/MyTipes/DrugstoreMedicines"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:bpmn="http://schemas.oracle.com/bpm/xpath"
                xmlns:ns3="http://xmlns.oracle.com/bpm/bpmobject/MyTipes/SetOfDrugstoreMedicines"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl ns0 bpmo ns1 xsd ns4 ns2 ns3 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref bpmn ldap">
  <xsl:template match="/">
    <ns3:SetOfDrugstoreMedicines>
      <xsl:for-each select="/ns0:SetOfDrugstores/ns0:drugstores">
        <ns3:drugstore_medicines_list>
          <ns2:drugstore_id>
            <xsl:if test="ns1:id/@xsi:nil">
              <xsl:attribute name="xsi:nil">
                <xsl:value-of select="ns1:id/@xsi:nil"/>
              </xsl:attribute>
            </xsl:if>
            <xsl:value-of select="ns1:id"/>
          </ns2:drugstore_id>
          <ns2:drugstore_name>
            <xsl:if test="ns1:name/@xsi:nil">
              <xsl:attribute name="xsi:nil">
                <xsl:value-of select="ns1:name/@xsi:nil"/>
              </xsl:attribute>
            </xsl:if>
            <xsl:value-of select="ns1:name"/>
          </ns2:drugstore_name>
        </ns3:drugstore_medicines_list>
      </xsl:for-each>
    </ns3:SetOfDrugstoreMedicines>
  </xsl:template>
</xsl:stylesheet>
