<?xml version="1.0" encoding="UTF-8"?>
<con:wsdlEntry xmlns:con="http://www.bea.com/wli/sb/resources/config">
    <con:wsdl><![CDATA[<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/BPMServiceTest/Project1/getAllDrugstores_Service" name="getAllDrugstores_Service-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/BPMServiceTest/Project1/getAllDrugstores_Service" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/BPMServiceTest/Project1/getAllDrugstores_Service" location="getAllDrugstores_Service.wsdl"/>
  <binding name="getAllDrugstores_Service_ptt-binding" type="tns:getAllDrugstores_Service_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="getAllDrugstores_ServiceSelect">
      <soap:operation soapAction="getAllDrugstores_ServiceSelect"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="getAllDrugstores_Service-service">
    <port name="getAllDrugstores_Service-port" binding="tns:getAllDrugstores_Service_ptt-binding">
      <soap:address location="jca://myConnPoolForDB"/>
    </port>
  </service>
</definitions>]]></con:wsdl>
    <con:dependencies>
        <con:import location="getAllDrugstores_Service.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/BPMServiceTest/Project1/getAllDrugstores_Service">
            <con:wsdl ref="OSB_DB_ADAPTERS/getAllDrugstores_Service"/>
        </con:import>
    </con:dependencies>
    <con:targetNamespace>http://xmlns.oracle.com/pcbpel/adapter/db/BPMServiceTest/Project1/getAllDrugstores_Service</con:targetNamespace>
</con:wsdlEntry>