<?xml version="1.0" encoding="UTF-8"?>
<con:wsdlEntry xmlns:con="http://www.bea.com/wli/sb/resources/config">
    <con:wsdl><![CDATA[<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Adapters/BDAdapter/selectSeparateRegistry" name="selectSeparateRegistry-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Adapters/BDAdapter/selectSeparateRegistry" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Adapters/BDAdapter/selectSeparateRegistry" location="selectSeparateRegistry.wsdl"/>
  <binding name="selectSeparateRegistry_ptt-binding" type="tns:selectSeparateRegistry_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="selectSeparateRegistrySelect">
      <soap:operation soapAction="selectSeparateRegistrySelect"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="selectSeparateRegistry-service">
    <port name="selectSeparateRegistry-port" binding="tns:selectSeparateRegistry_ptt-binding">
      <soap:address location="jca://myConnPoolForDB"/>
    </port>
  </service>
</definitions>]]></con:wsdl>
    <con:dependencies>
        <con:import location="selectSeparateRegistry.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Adapters/BDAdapter/selectSeparateRegistry">
            <con:wsdl ref="test4/selectSeparateRegistry/selectSeparateRegistry"/>
        </con:import>
    </con:dependencies>
    <con:targetNamespace>http://xmlns.oracle.com/pcbpel/adapter/db/Adapters/BDAdapter/selectSeparateRegistry</con:targetNamespace>
</con:wsdlEntry>