<?binding.jca service2_db.jca?>
<wsdl:definitions name="service2" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Adapters/BDAdapter/service2" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Adapters/BDAdapter/service2" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/service2"
                  xmlns:jca="http://schemas.xmlsoap.org/wsdl/jca/"
                  xmlns:format="http://schemas.xmlsoap.org/wsdl/formatbinding/"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <plt:partnerLinkType name="service2_plt">
        <plt:role name="service2_role">
            <plt:portType name="tns:service2_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/service2" schemaLocation="xsd/service2_table.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="service2Select_inputParameters">
        <wsdl:part name="service2Select_inputParameters" element="top:service2SelectInputParameters"/>
    </wsdl:message>
    <wsdl:message name="ProductCollection_msg">
        <wsdl:part name="ProductCollection" element="top:ProductCollection"/>
    </wsdl:message>
    <wsdl:portType name="service2_ptt">
        <wsdl:operation name="service2Select">
            <wsdl:input message="tns:service2Select_inputParameters"/>
            <wsdl:output message="tns:ProductCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
